name: Auto Assign Reviewers

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest

    steps:
      - name: Determine reviewers
        env:
          AUTHOR: ${{ github.actor }}
        run: |
          declare -A REVIEWER_MAP=(
            ["kim-1997"]="almighty55555 lee-nakyung"
            ["almighty55555"]="lee-nakyung yujin0408"
            ["lee-nakyung"]="yujin0408 jeonghwanJay"
            ["yujin0408"]="jeonghwanJay kim-1997"
            ["jeonghwanJay"]="kim-1997 almighty55555"
          )

          REVIEWERS=${REVIEWER_MAP[$AUTHOR]}
          if [ -z "$REVIEWERS" ]; then
            echo "No reviewers configured for user: $AUTHOR"
            exit 0
          fi

          JSON=$(jq -n --argjson arr "$(echo [$(
              for user in $REVIEWERS; do echo "\"$user\""; done | paste -sd,
          )]" '$arr | {reviewers: .}')

          echo "Requesting reviewers: $REVIEWERS"
          curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
            -d "$JSON"
